apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  source:
    repoURL: https://github.com/hoangcuteday/k8s-argocd.git
    targetRevision: main
    path: apps/k8s-api
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
