---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: api-email-alerts
  namespace: default
  labels:
    app: api
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: '4'
spec:
  route:
    receiver: personal-email
    groupBy:
      - alertname
      - namespace
      - service
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    matchers:
      - name: alertname
        value: ApiHas5xxResponses
        matchType: '='
      - name: severity
        value: warning
        matchType: '='
      - name: service
        value: api-service
        matchType: '='

  receivers:
    - name: personal-email
      emailConfigs:
        - to: 'mn456897@gmail.com'
          from: 'khanhle11342@gmail.com'
          smarthost: 'smtp.gmail.com:587'
          authUsername: 'khanhle11342@gmail.com'
          authPassword:
            name: alertmanager-smtp
            key: password
          requireTLS: true
          sendResolved: true

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-500-alert-rules
  namespace: default
  labels:
    app: api
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  groups:
    - name: api.http-errors
      rules:
        - alert: ApiHas5xxResponses
          expr: |
            sum by (namespace, service) (
              increase(http_requests_total{
                namespace="default",
                service="api-service",
                status=~"5.."
              }[1m])
            ) > 0
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: 'API returned HTTP 5xx responses'
            description: 'api-service returned at least one HTTP 5xx response in the last 1 minute.'
