apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-rollout
  namespace: default
  labels:
    app: api
spec:
  replicas: 2

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: hoangcute19/w9-api:v1
          ports:
            - containerPort: 8080
          env:
            - name: ERROR_RATE
              value: '0'
            - name: VERSION
              value: 'v2'
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 10s
        - setWeight: 100
